# Site settings
author: cailee
title: hello
header-img: img/home-bg.png
email: cailee.adamson+animalsnakes@wework.com
copyright_name: cailee
description: > # this means to ignore newlines until "baseurl:"
  bloggy
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  smoothiesareyummy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
